package io.orazzu.android_course.repository.local

import io.orazzu.android_course.model.app.AppCategory
import io.orazzu.android_course.model.app.AppDetails
import io.orazzu.android_course.repository.AppRepository

class AppLocalRepository : AppRepository {
    override fun getApps(): List<AppDetails> = listOf(
        AppDetails(
            id = "2q34rf",
            name = "Сбербанк Онлайн — с Салютом",
            developer = "Сбер",
            category = AppCategory.FINANCE,
            ageRating = 14,
            iconUrl = "https://cdn-app.sberdevices.ru/asset/sites_240:q80/aHR0cHM6Ly9jZG4uc2JlcmRldmljZXMucnUvc3RhdGljL3NlcnZpY2VzL3RhcmdldC81ZDliOWFlNy0zMDVmLTRkNzgtOWY0NS01ZTZiOTU5N2JlOTAvZTNhZjU5NjQtOTNjMi00ODdhLWE4ODItNGU0NTY2MWI5ZmI5LnBuZw==",
            screenshotUrlList = listOf(),
            description = "Больше чем банк",
        ),
        AppDetails(
            id = "24rа2f",
            name = "Яндекс.Браузер — с Алисой",
            developer = "Яндекс",
            category = AppCategory.UTILITIES,
            ageRating = 0,
            iconUrl = "https://play-lh.googleusercontent.com/CNo_xqkAu1TPcO6Y02JAVIE1-1IoF6VlEnUgIv7MPby4H52Jn54Iu_-tg69Z91n0QVxDyZCwijRV2AFZwizf_Q=s96",
            screenshotUrlList = listOf(),
            description = "Быстрый и безопасный браузер",
        ),
        AppDetails(
            id = "klj349",
            name = "Почта Mail.ru",
            developer = "VK",
            category = AppCategory.UTILITIES,
            ageRating = 0,
            iconUrl = "https://play-lh.googleusercontent.com/Q6AOumT71kEeuc_E359gdspTzWGjWP3jzmNBMRbI7drhRHCtEwYD7VLw88l0QotoboC6CrgFuXg8pr4CtASG3g",
            screenshotUrlList = listOf(),
            description = "Почтовый клиент для любых ящиков",
        ),
        AppDetails(
            id = "274rgw",
            name = "Яндекс.Навигатор",
            developer = "Яндекс",
            category = AppCategory.MAPS,
            ageRating = 0,
            iconUrl = "https://play-lh.googleusercontent.com/aROhxD1HNPLqW1ZiQzCxhDmx700j2g1VGZ0DPDualQxATkCkUEOWWCxxq0BSnZ3fynEe",
            screenshotUrlList = listOf(),
            description = "Парковки и заправки — по пути",
        ),
        AppDetails(
            id = "34ie9c",
            name = "Мой МТС",
            developer = "МТС",
            category = AppCategory.UTILITIES,
            ageRating = 0,
            iconUrl = "https://play-lh.googleusercontent.com/oO7fsxw5F8fItT4fScnFG9JSCghkoIbOibyx8WpHN8QReoeFKHNlIfLTvDO6BD7OSw",
            screenshotUrlList = listOf(),
            description = "Мой МТС — центр экосистемы МТС",
        ),
        AppDetails(
            id = "tyft6u",
            name = "Яндекс — с Алисой",
            developer = "Яндекс",
            category = AppCategory.UTILITIES,
            ageRating = 0,
            iconUrl = "https://play-lh.googleusercontent.com/K1yQPVuQDv3x87tPgQGPsnqdoDVWssiLb7P2sjyr2_rjjJHOKgfIaqa6LgwFaqq6lp_DOy4ACCWvn_fJwWKjpQ",
            screenshotUrlList = listOf(),
            description = "Яндекс — поиск всегда под рукой",
        ),
        AppDetails(
            id = "13er23",
            name = "Some App",
            developer = "Some Bank",
            category = AppCategory.FINANCE,
            ageRating = 17,
            iconUrl = "https://yavuzceliker.github.io/sample-images/image-7.jpg",
            screenshotUrlList = listOf(),
            description = "Just some",
        ),
        AppDetails(
            id = "43fr",
            name = "One More App",
            developer = "Someone",
            category = AppCategory.EDUCATION,
            ageRating = 0,
            iconUrl = "https://yavuzceliker.github.io/sample-images/image-410.jpg",
            screenshotUrlList = listOf(),
            description = "Just another",
        ),
        AppDetails(
            id = "eg8u4a",
            name = "An App With a Crazy Long Name–Who in the World Ever Comes up With Such Blankets?",
            developer = "Some Studio That Names Its Apps Like They’re Emo Songs–and Even Names Itself That Way",
            category = AppCategory.ENTERTAINMENT,
            ageRating = 17,
            iconUrl = "https://yavuzceliker.github.io/sample-images/image-910.jpg",
            screenshotUrlList = listOf(),
            description = "Our descriptions are also long as hell btw. Y’all never read them anyways tho.",
        ),
    )
}
